name: Deploy to Tsuru

on:
  push:
    branches:
      - master  # Trigger on push to the main branch. Change this as needed.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Install Tsuru CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/tsuru/tsuru-client/master/install.sh | sh
          echo "Tsuru CLI installed"

      - name: Authenticate with Tsuru
        env:
          TSURU_TOKEN: ${{ secrets.TSURU_TOKEN }}
          TSURU_HOST: ${{ secrets.TSURU_HOST }}
        run: |
          echo "TSURU_TOKEN=${{ secrets.TSURU_TOKEN }}" >> $GITHUB_ENV
          tsuru target-add default https://impaas.uk -s
          echo "Authenticated with Tsuru"
      - name: Rename war file
        run: |
          mv ./build/libs/Applet-1.0-SNAPSHOT.war ./ROOT.war

      - name: Show info
        env:
          TSURU_HOST: "https://impaas.uk"
          TSURU_TOKEN: "ba5b475307064346015ccfbeaa7662a78a13d7af47167993b574a8f17d7af4a2"
        run: |
          tsuru login
          tsuru app-info -a applet

      - name: Deploy to Tsuru
        env:
          TSURU_TOKEN: ${{ secrets.TSURU_TOKEN }}
        run: |
          tsuru app-deploy -a applet ROOT.war
