name: Deploy to Tsuru

on:
  push:
    branches:
      - master  # Trigger on push to the main branch. Change this as needed.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Tsuru CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/tsuru/tsuru-client/master/install.sh | sh
          echo "Tsuru CLI installed"

      - name: Authenticate with Tsuru
        env:
          TSURU_TOKEN: ${{ secrets.TSURU_TOKEN }}
          TSURU_HOST: ${{ secrets.TSURU_HOST }}
        run: |
          echo "Target and token"
          echo $TSURU_TARGET
          echo $TSURU_TOKEN
          echo "Printed"
          tsuru target-add default https://impaas.uk -s
          tsuru login --token $TSURU_TOKEN
          echo "Authenticated with Tsuru"

      - name: Deploy to Tsuru
        env:
          TSURU_TOKEN: ${{ secrets.TSURU_TOKEN }}
        run: |
          tsuru app-deploy . -a myapp -y -m "GitHub Actions deployment"
